In [11]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [62]:
%run ../python/selfish_routing.py

In [63]:
test = MoranProcess([[3, 0], [4, 1]], w=5, mutation_probability=0.001, population_array=[60, 40])

In [64]:
df = test.run_time_series(10000, 10)

In [70]:
df

TimeStep    (A, B)
0            0  [60, 40]
1           10  [54, 46]
2           20  [50, 50]
3           30  [48, 52]
4           40  [46, 54]
5           50  [41, 59]
6           60  [38, 62]
7           70  [36, 64]
8           80  [34, 66]
9           90  [30, 70]
10         100  [27, 73]
11         110  [24, 76]
12         120  [23, 77]
13         130  [20, 80]
14         140  [19, 81]
15         150  [18, 82]
16         160  [17, 83]
17         170  [15, 85]
18         180  [14, 86]
19         190  [11, 89]
20         200  [11, 89]
21         210  [11, 89]
22         220  [11, 89]
23         230  [10, 90]
24         240   [9, 91]
25         250   [8, 92]
26         260   [7, 93]
27         270   [4, 96]
28         280   [3, 97]
29         290   [3, 97]
...        ...       ...
971       9710  [0, 100]
972       9720  [0, 100]
973       9730  [0, 100]
974       9740  [0, 100]
975       9750  [0, 100]
976       9760  [0, 100]
977       9770  [0, 100]
978       9780  [0, 100]
979       9790  [0, 100]
980       9800  [0, 100]
981       9810  [0, 100]
982       9820  [0, 100]
983       9830  [0, 100]
984       9840  [0, 100]
985       9850  [0, 100]
986       9860  [0, 100]
987       9870  [0, 100]
988       9880  [0, 100]
989       9890  [0, 100]
990       9900   [1, 99]
991       9910   [1, 99]
992       9920   [1, 99]
993       9930   [1, 99]
994       9940   [1, 99]
995       9950  [0, 100]
996       9960  [0, 100]
997       9970  [0, 100]
998       9980  [0, 100]
999       9990  [0, 100]
1000     10000  [0, 100]

[1001 rows x 2 columns]

In [ ]:
pd.DataFrame()

In [14]:
df = test.run_time_series(1000, 10)

ValueError: probabilities are not non-negative

array([[73, 30],
       [58, 52]])

In [15]:
no_u - (2*no_u-1)*0.001

array([ 0.6996,  0.3004])

In [16]:
sum(_)

1.0

In [37]:
p = np.array([ -2.26283317e-05,1.00002263e+00])
p

array([ -2.26283317e-05,   1.00002263e+00])

In [32]:
p =p.astype(float32)

In [38]:
np.sum(p, )

1.0000000016682999

In [34]:
p=p/np.sum(p)

In [35]:
p

array([ -2.26283319e-05,   1.00002265e+00], dtype=float32)

In [36]:
print(p)
np.random.choice([1, 2], p= p)

[ -2.26283319e-05   1.00002265e+00]


ValueError: probabilities are not non-negative