In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
my_array = np.array([1, 1, 2, 2, 1, 1])

In [4]:
len(np.where(my_array == 1))

1

In [15]:
%%timeit
array = 3*np.array([2, 3])
a = np.exp(array[0])
b= np.exp(array[1])

The slowest run took 13.80 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 3.93 µs per loop


In [18]:
%%timeit
array = 3*np.array([2, 3])
a, b = np.exp(array)

The slowest run took 11.92 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 4.06 µs per loop


In [10]:
np.exp(9)

8103.0839275753842

In [73]:
%run ../python/selfish_routing.py

In [76]:
test = MoranProcess(2, 10, 1, 2, 3, 4, 5)

In [77]:
test.population

array([ 1.,  1.,  1.,  2.,  2.,  1.,  1.,  1.,  1.,  2.])

In [78]:
for i in range(1, 10):
    test.step()

Initial population
[ 1.  1.  1.  2.  2.  1.  1.  1.  1.  2.]
Individual selected and died
Population after the death
[ 1.  1.  2.  2.  1.  1.  1.  1.  2.]
Individual reproduced based upon the fitness function
[ 1.  1.  2.  2.  1.  1.  1.  1.  2.  1.]


Initial population
[ 1.  1.  2.  2.  1.  1.  1.  1.  2.  1.]
Individual selected and died
Population after the death
[ 1.  2.  2.  1.  1.  1.  1.  2.  1.]
Individual reproduced based upon the fitness function
[ 1.  2.  2.  1.  1.  1.  1.  2.  1.  1.]


Initial population
[ 1.  2.  2.  1.  1.  1.  1.  2.  1.  1.]
Individual selected and died
Population after the death
[ 1.  2.  1.  1.  1.  1.  2.  1.  1.]
Individual reproduced based upon the fitness function
[ 1.  2.  1.  1.  1.  1.  2.  1.  1.  1.]


Initial population
[ 1.  2.  1.  1.  1.  1.  2.  1.  1.  1.]
Individual selected and died
Population after the death
[ 1.  1.  1.  1.  1.  2.  1.  1.  1.]
Individual reproduced based upon the fitness function
[ 1.  1.  1.  1.  1.  2.  1.  1.

In [34]:
probability_distribution = test._MoranProcess__compute_fitness()
probability_distribution

(0.36457644074163931, 0.63542355925836058)

In [72]:
np.random.choice([1, 2], p= (0.5, 0.5))

2

In [32]:
np.choose(1, [1, 2], p=probability_distribution)

TypeError: choose() got an unexpected keyword argument 'p'