In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
matrix  = np.array([[1, 2], [3, 4]])

In [5]:
matrix.shape[0] == matrix.shape[1]

True

In [7]:
population = np.array([3, 7])

In [12]:
population_size = np.sum(population)

In [20]:
payoff_vector = (np.dot(matrix, population)-np.diag(matrix))/ (population_size-1)
payoff_vector

array([ 1.77777778,  3.66666667])

In [23]:
fitness_vector = np.exp(0.2*payoff_vector)
fitness_vector

array([ 1.4269732 ,  2.08200908])

In [25]:
probabilities = population*fitness_vector
probabilities =  probabilities/np.sum(probabilities)
probabilities

array([ 0.22704447,  0.77295553])

In [15]:
a=1
b=2
c=3
d=4
temp_a1 = ((population[0] - 1) * a) / (population_size - 1)
temp_a2 = (population[1] * b) / (population_size - 1)
payoff_of_a = temp_a1 + temp_a2
temp_b1 = (population[0] *c) / (population_size - 1)
temp_b2 = ((population[1] - 1) * d) / (population_size - 1)
payoff_of_b = temp_b1 + temp_b2
print(payoff_of_a, payoff_of_b)

1.77777777778 3.66666666667


In [89]:
%run ../python/selfish_routing.py

Initial population
[5 7]
Individual selected and died
Population after the death
[5 6]
4.86469782974
-3.86469782974


ValueError: probabilities are not non-negative

In [82]:
test.population

array([5, 7])

In [83]:
test.population_size

12

In [84]:
np.random.choice(range(2), p=(0.5, 0.5))

0

In [87]:
test = MoranProcess(2, 1, 2, 3, 4, 5, [5, 7])

In [88]:
for i in range(1, 10):
    test.step()

Initial population
[5 7]
Individual selected and died
Population after the death
[5 6]


ValueError: probabilities are not non-negative

In [34]:
probability_distribution = test._MoranProcess__compute_fitness()
probability_distribution

(0.36457644074163931, 0.63542355925836058)

In [72]:
np.random.choice([1, 2], p= (0.5, 0.5))

2

In [32]:
np.choose(1, [1, 2], p=probability_distribution)

TypeError: choose() got an unexpected keyword argument 'p'

In [11]:
population_array = [1, 2.4, 3.2]

In [12]:
np.array(population_array, dtype=int)

array([1, 2, 3])

In [13]:
np.sum(_)

6